command_map_hs = [("\\textg", ("g", "insitu")),
     ("\\textcrh", ("ħ", "insitu")),
     ("\\textturna", ("ɐ", "insitu")),
     ("\\textscripta", ("ɑ", "insitu")),
     ("\\textturnscripta", ("ɒ", "insitu")),
     ("\\texthtb", ("ɓ", "insitu")),
     ("\\textopeno", ("ɔ", "insitu")),
     ("\\textctc", ("ɕ", "insitu")),
     ("\\textrtaild", ("ɖ", "insitu")),
     ("\\texthtd", ("ɗ", "insitu")),
     ("\\textreve", ("ɘ", "insitu")),
     ("\\textrhookschwa", ("ɚ", "insitu")),
     ("\\textepsilon", ("ɛ", "insitu")),
     ("\\textrevepsilon", ("ɜ", "insitu")),
     ("\\textrhookrevepsilon", ("ɝ", "insitu")),
     ("\\textcloserevepsilon", ("ɞ", "insitu")),
     ("\\textbardotlessj", ("ɟ", "insitu")),
     ("\\texthtg", ("ɠ", "insitu")),
     ("\\textscriptg", ("ɡ", "insitu")),
     ("\\textscg", ("ɢ", "insitu")),
     ("\\textgamma", ("ɣ", "insitu")),
     ("\\textramshorns", ("ɤ", "insitu")),
     ("\\textturnh", ("ɥ", "insitu")),
     ("\\texthth", ("ɦ", "insitu")),
     ("\\texththeng", ("ɧ", "insitu")),
     ("\\textbari", ("ɨ", "insitu")),
     ("\\textiota", ("ɩ", "insitu")),
     ("\\textsci", ("ɪ", "insitu")),
     ("\\textltilde", ("ɫ", "insitu")),
     ("\\textbeltl", ("ɬ", "insitu")),
     ("\\textrtaill", ("ɭ", "insitu")),
     ("\\textlyoghlig", ("ɮ", "insitu")),
     ("\\textturnm", ("ɯ", "insitu")),
     ("\\textturnmrleg", ("ɰ", "insitu")),
     ("\\textltailm", ("ɱ", "insitu")),
     ("\\textltailn", ("ɲ", "insitu")),
     ("\\textrtailn", ("ɳ", "insitu")),
     ("\\textscn", ("ɴ", "insitu")),
     ("\\textbaro", ("ɵ", "insitu")),
     ("\\textscoelig", ("ɶ", "insitu")),
     ("\\textcloseomega", ("ɷ", "insitu")),
     ("\\textphi", ("ɸ", "insitu")),
     ("\\textturnr", ("ɹ", "insitu")),
     ("\\textturnlonglegr", ("ɺ", "insitu")),
     ("\\textturnrrtail", ("ɻ", "insitu")),
     ("\\textlonglegr", ("ɼ", "insitu")),
     ("\\textrtailr", ("ɽ", "insitu")),
     ("\\textfishhookr", ("ɾ", "insitu")),
     ("\\textlhti", ("ɿ", "insitu")),
     ("\\textscr", ("ʀ", "insitu")),
     ("\\textinvscr", ("ʁ", "insitu")),
     ("\\textrtails", ("ʂ", "insitu")),
     ("\\texthtbardotlessj", ("ʄ", "insitu")),
     ("\\textraisevibyi", ("ʅ", "insitu")),
     ("\\textctesh", ("ʆ", "insitu")),
     ("\\textturnt", ("ʇ", "insitu")),
     ("\\textrtailt", ("ʈ", "insitu")),
     ("\\textbaru", ("ʉ", "insitu")),
     ("\\textupsilon", ("ʊ", "insitu")),
     ("\\textscriptv", ("ʋ", "insitu")),
     ("\\textturnv", ("ʌ", "insitu")),
     ("\\textturnw", ("ʍ", "insitu")),
     ("\\textturny", ("ʎ", "insitu")),
     ("\\textscy", ("ʏ", "insitu")),
     ("\\textrtailz", ("ʐ", "insitu")),
     ("\\textctz", ("ʑ", "insitu")),
     ("\\textyogh", ("ʒ", "insitu")),
     ("\\textctyogh", ("ʓ", "insitu")),
     ("\\textglotstop", ("ʔ", "insitu")),
     ("\\textrevglotstop", ("ʕ", "insitu")),
     ("\\textinvglotstop", ("ʖ", "insitu")),
     ("\\textstretchc", ("ʗ", "insitu")),
     ("\\textbullseye", ("ʘ", "insitu")),
     ("\\textscb", ("ʙ", "insitu")),
     ("\\textcloseepsilon", ("ʚ", "insitu")),
     ("\\texthtscg", ("ʛ", "insitu")),
     ("\\textsch", ("ʜ", "insitu")),
     ("\\textctj", ("ʝ", "insitu")),
     ("\\textturnk", ("ʞ", "insitu")),
     ("\\textscl", ("ʟ", "insitu")),
     ("\\texthtq", ("ʠ", "insitu")),
     ("\\textbarglotstop", ("ʡ", "insitu")),
     ("\\textbarrevglotstop", ("ʢ", "insitu")),
     ("\\textdzlig", ("ʣ", "insitu")),
     ("\\textdyoghlig", ("ʤ", "insitu")),
     ("\\textdctzlig", ("ʥ", "insitu")),
     ("\\texttslig", ("ʦ", "insitu")),
     ("\\textteshlig", ("ʧ", "insitu")),
     ("\\texttctclig", ("ʨ", "insitu")),
     ("\\textprimstress", ("ˈ", "insitu")),
     ("\\textlengthmark", ("ː", "insitu")),
     ("\\textbeta", ("β", "insitu")),
     ("\\texttheta", ("θ", "insitu")),
     ("\\textlambda", ("λ", "insitu")),
     ("\\textchi", ("χ", "insitu")),
     ("\\textomega", ("ω", "insitu")),
     ("\\textsuperscript\texthth", ("ʱ", "insitu")),
     ("\\textsuperscript\textturnr", ("ʴ", "insitu")),
     ("\\textsuperscript\textturnrrtail", ("ʵ", "insitu")),
     ("\\textsuperscript\textinvscr", ("ʶ", "insitu")),
     ("\\tone5", ("˥", "insitu")),
     ("\\tone4", ("˦", "insitu")),
     ("\\tone3", ("˧", "insitu")),
     ("\\tone2", ("˨", "insitu")),
     ("\\tone1", ("˩", "insitu")),
     ("\\texthbar", ("ħ", "insitu")),
     ("\\ng", ("ŋ", "insitu")),
     ("\\c{c}", ("ç", "insitu")),
     ("\\`", ("̀", "postfix")),
     ("\\'", ("́", "postfix")),
     ("\\^", ("̂", "postfix")),
     ("\\~", ("̃", "postfix")),
     ("\\=", ("̄", "postfix")),
     ("\\textoverline", ("̅", "postfix")),
     ("\\u", ("̆", "postfix")),
     ("\\.", ("̇", "postfix")),
     ("\\\"", ("̈", "postfix")),
     ("\\m", ("̉", "postfix")),
     ("\\texthookabove", ("̉", "postfix")),
     ("\\r", ("̊", "postfix")),
     ("\\H", ("̋", "postfix")),
     ("\\v", ("̌", "postfix")),
     ("\\textvbaraccent", ("̍", "postfix")),
     ("\\textdoublevbaraccent", ("̎", "postfix")),
     ("\\U", ("̎", "postfix")),
     ("\\textdoublegrave", ("̏", "postfix")),
     ("\\G", ("̏", "postfix")),
     ("\\textdotbreve", ("̐", "postfix")),
     ("\\textroundcap", ("̑", "postfix")),
     ("\\newtie", ("̑", "postfix")),
     ("\\t", ("̑", "postfix")),
     ("\\textturncommaabove", ("̒", "postfix")),
     ("\\textcommaabove", ("̓", "postfix")),
     ("\\textrevcommaabove", ("̔", "postfix")),
     ("\\textcommaabover", ("̕", "postfix")),
     ("\\textsubgrave", ("̖", "postfix")),
     ("\\textsubacute", ("̗", "postfix")),
     ("\\textadvancing", ("̘", "postfix")),
     ("\\textretracting", ("̙", "postfix")),
     ("\\textlangleabove", ("̚", "postfix")),
     ("\\textrighthorn", ("̛", "postfix")),
     ("\\textsublhalfring", ("̜", "postfix")),
     ("\\textraising", ("̝", "postfix")),
     ("\\textlowering", ("̞", "postfix")),
     ("\\textsubplus", ("̟", "postfix")),
     ("\\textsubminus", ("̠", "postfix")),
     ("\\textpalhookbelow", ("̡", "postfix")),
     ("\\M", ("̢", "postfix")),
     ("\\textrethookbelow", ("̢", "postfix")),
     ("\\d", ("̣", "postfix")),
     ("\\textsubdot", ("̣", "postfix")),
     ("\\textsubumlaut", ("̤", "postfix")),
     ("\\textsubring", ("̥", "postfix")),
     ("\\textcommabelow", ("̦", "postfix")),
     ("\\c", ("̧", "postfix")),
     ("\\k", ("̨", "postfix")),
     ("\\textpolhook", ("̨", "postfix")),
     ("\\textsyllabic", ("̩", "postfix")),
     ("\\textsubbridge", ("̪", "postfix")),
     ("\\textsubw", ("̫", "postfix")),
     ("\\textsubwedge", ("̬", "postfix")),
     ("\\textsubcircum", ("̭", "postfix")),
     ("\\textundertie", ("̮", "postfix")),
     ("\\textsubarch", ("̯", "postfix")),
     ("\\textsubtilde", ("̰", "postfix")),
     ("\\textsubbar", ("̱", "postfix")),
     ("\\b", ("̲", "postfix")),
     ("\\subdoublebar", ("̳", "postfix")),
     ("\\textsuperimposetilde", ("̴", "postfix")),
     ("\\B", ("̵", "postfix")),
     ("\\textsstrokethru", ("̵", "postfix")),
     ("\\textlstrokethru", ("̶", "postfix")),
     ("\\textsstrikethru", ("̷", "postfix")),
     ("\\textlstrikethru", ("̸", "postfix")),
     ("\\textsubrhalfring", ("̹", "postfix")),
     ("\\textinvsubbridge", ("̺", "postfix")),
     ("\\textsubsquare", ("̻", "postfix")),
     ("\\textseagull", ("̼", "postfix")),
     ("\\textovercross", ("̽", "postfix")),
     ("\\overbridge", ("͆", "postfix")),
     ("\\subdoublevert", ("͈", "postfix")),
     ("\\subcorner", ("͉", "postfix")),
     ("\\textoverw", ("͊", "postfix")),
     ("\\crtilde", ("͊", "postfix")),
     ("\\dottedtilde", ("͋", "postfix")),
     ("\\doubletilde", ("͌", "postfix")),
     ("\\spreadlips", ("͍", "postfix")),
     ("\\whistle", ("͎", "postfix")),
     ("\\textgraphemejoin", ("͏", "postfix")),
     ("\\textrightarrowhead", ("͐", "postfix")),
     ("\\textlefthalfring", ("͑", "postfix")),
     ("\\sublptr", ("͔", "postfix")),
     ("\\subrptr", ("͕", "postfix")),
     ("\\textrightuparrowhead", ("͖", "postfix")),
     ("\\textrighthalfring", ("͗", "postfix")),
     ("\\textdoublebreve", ("͝", "postfix")),
     ("\\textdoublemacron", ("͞", "postfix")),
     ("\\textdoublemacronbelow", ("͟", "postfix")),
     ("\\textdoubletilde", ("͠", "postfix")),
     ("\\texttoptiebar", ("͡", "postfix")),
     ("\\sliding", ("͢", "postfix")),
     ("\\superh", ("ʰ", "insitu")),
     ("\\superH", ("ʱ", "insitu")),
     ("\\superj", ("ʲ", "insitu")),
     ("\\superr", ("ʳ", "insitu")),
     ("\\superK", ("ʶ", "insitu")),
     ("\\superw", ("ʷ", "insitu")),
     ("\\supery", ("ʸ", "insitu")),
     ("\\super?", ("ˀ", "insitu")),
     ("\\superG", ("ˠ", "insitu")),
     ("\\superl", ("ˡ", "insitu")),
     ("\\supers", ("ˢ", "insitu")),
     ("\\superx", ("ˣ", "insitu")),
     ("\\superQ", ("ˤ", "insitu")),
     ("\\H*", ("̏", "postfix")),
     ("\\`*", ("̖", "postfix")),
     ("\\'*", ("̗", "postfix")),
     ("\\^*", ("̭", "postfix")),
     ("\\|c", ("̑", "postfix")),
     ("\\|[", ("̪", "postfix")),
     ("\\|]", ("̺", "postfix")),
     ("\\|)", ("̹", "postfix")),
     ("\\|(", ("̜", "postfix")),
     ("\\|w", ("̫", "postfix")),
     ("\\|m", ("̼", "postfix")),
     ("\\|x", ("̽", "postfix")),
     ("\\|+", ("̟", "postfix")),
     ("\\|'", ("̝", "postfix")),
     ("\\|`", ("̞", "postfix")),
     ("\\|<", ("̘", "postfix")),
     ("\\|>", ("̙", "postfix")),
     ("\\~*", ("̰", "postfix")),
     ("\\\"*", ("̤", "postfix")),
     ("\\r*", ("̥", "postfix")),
     ("\\v*", ("̬", "postfix")),
     ("\\=*", ("̱", "postfix")),
     ("\\;G", ("ɢ", "insitu")),
     ("\\;R", ("ʀ", "insitu")),
     ("\\;L", ("ʟ", "insitu")),
     ("\\;N", ("ɴ", "insitu"))]

letter_map_hs = [("0", "ʉ"),
   ("1", "ɨ"),
   ("2", "ʌ"),
   ("3", "ɜ"),
   ("4", "ɥ"),
   ("5", "ɐ"),
   ("6", "ɒ"),
   ("7", "ɤ"),
   ("8", "ɵ"),
   ("9", "ɘ"),
   ("@", "ə"),
   ("A", "ɑ"),
   ("B", "β"),
   ("C", "ɕ"),
   ("D", "ð"),
   ("E", "ε"),
   ("F", "φ"),
   ("G", "γ"),
   ("H", "ɦ"),
   ("I", "ɪ"),
   ("J", "ʝ"),
   ("K", "ʁ"),
   ("L", "ʎ"),
   ("M", "ɱ"),
   ("N", "ŋ"),
   ("O", "ɔ"),
   ("P", "ʔ"),
   ("Q", "ʕ"),
   ("R", "ɾ"),
   ("S", "ʃ"),
   ("T", "θ"),
   ("U", "υ"),
   ("V", "ʋ"),
   ("W", "ɯ"),
   ("X", "χ"),
   ("Y", "ʏ"),
   ("Z", "ʒ"),
   ("g", "ɡ"),
   ("\"", "ˈ"),
   (":", "ː")]


def get_command_map():
    return command_map_hs

def get_letter_map():
    return letter_map_hs